###################### Filebeat Configuration ############################
# This file configures Filebeat to send Wazuh alerts to the Wazuh Indexer
# Uses environment variables for authentication to prevent hardcoded credentials
###########################################################################

# Wazuh - Filebeat configuration file
output.elasticsearch:
  hosts: ["wazuh-indexer:9200"]
  protocol: https
  username: ${INDEXER_USERNAME}
  password: ${INDEXER_PASSWORD}

  # SSL Configuration
  ssl.enabled: true
  ssl.verification_mode: full
  ssl.certificate_authorities: ["/etc/ssl/root-ca.pem"]
  ssl.certificate: "/etc/ssl/filebeat.pem"
  ssl.key: "/etc/ssl/filebeat-key.pem"

  # Index Configuration
  indices:
    - index: "wazuh-alerts-4.x-%{+yyyy.MM.dd}"

# Filebeat modules
filebeat.modules:
  - module: wazuh
    alerts:
      enabled: true

# Custom settings
setup.template.json.enabled: true
setup.template.json.path: '/etc/filebeat/wazuh-template.json'
setup.template.json.name: 'wazuh'
setup.template.overwrite: true
setup.ilm.enabled: false

# Logging
logging.level: info
logging.to_files: true
logging.files:
  path: /var/log/filebeat
  name: filebeat
  keepfiles: 7
  permissions: 0644

# Performance tuning
queue.mem:
  events: 4096
  flush.min_events: 512
  flush.timeout: 5s

output.elasticsearch.bulk_max_size: 2048
output.elasticsearch.worker: 2

# Processor settings
processors:
  - add_host_metadata:
      when.not.contains.tags: forwarded
  - add_cloud_metadata: ~
  - add_docker_metadata: ~
