"""
Startup and Integration Tests
Alert Triage Service

Verifies the service can start and respond to basic requests.
"""

import pytest
from unittest.mock import patch, AsyncMock
from fastapi.testclient import TestClient


def test_import_main():
    """Test that main module can be imported without errors"""
    try:
        from services.alert_triage import main
        assert main.app is not None
    except Exception as e:
        pytest.fail(f"Failed to import main module: {e}")


def test_import_models():
    """Test that models module can be imported"""
    try:
        from services.alert_triage import models
        assert models.SecurityAlert is not None
        assert models.TriageResponse is not None
    except Exception as e:
        pytest.fail(f"Failed to import models module: {e}")


def test_import_llm_client():
    """Test that llm_client module can be imported"""
    try:
        from services.alert_triage import llm_client
        assert llm_client.OllamaClient is not None
    except Exception as e:
        pytest.fail(f"Failed to import llm_client module: {e}")


def test_import_ml_client():
    """Test that ml_client module can be imported"""
    try:
        from services.alert_triage import ml_client
        assert ml_client.MLInferenceClient is not None
    except Exception as e:
        pytest.fail(f"Failed to import ml_client module: {e}")


def test_import_config():
    """Test that config module can be imported"""
    try:
        from services.alert_triage import config
        assert config.settings is not None
        assert config.settings.service_name == "alert-triage"
    except Exception as e:
        pytest.fail(f"Failed to import config module: {e}")


def test_fastapi_app_creation():
    """Test that FastAPI app is created successfully"""
    from services.alert_triage.main import app

    assert app is not None
    assert app.title == "Alert Triage Service"


def test_openapi_schema():
    """Test that OpenAPI schema is generated"""
    from services.alert_triage.main import app

    schema = app.openapi()

    assert schema is not None
    assert "openapi" in schema
    assert "paths" in schema
    assert "/analyze" in schema["paths"]
    assert "/health" in schema["paths"]
    assert "/batch" in schema["paths"]


def test_service_routes():
    """Test that all expected routes are registered"""
    from services.alert_triage.main import app

    routes = [route.path for route in app.routes]

    assert "/" in routes
    assert "/health" in routes
    assert "/metrics" in routes
    assert "/analyze" in routes
    assert "/batch" in routes
    assert "/docs" in routes  # Auto-generated by FastAPI
    assert "/openapi.json" in routes  # Auto-generated by FastAPI
